name: Cache Dependencies

on:
  workflow_call:
    inputs:
      flutter-version:
        type: string
        description: "Flutter version to use"
        required: false
        default: "3.32.4"
      channel:
        type: string
        description: "Flutter channel to use"
        required: false
        default: "stable"

jobs:
  cache:
    name: Cache Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ inputs.flutter-version }}
          channel: ${{ inputs.channel }}

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
            build
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Install dependencies
        run: flutter pub get

      - name: Run build_runner
        run: flutter packages pub run build_runner build --delete-conflicting-outputs
